#!/bin/bash

# This script is called when a workflow exits (successfully or after failure)
# See https://pegasus.isi.edu/documentation/notifications.php

NOTIFICATION_EMAIL=$1

export PATH=$PEGASUS_BIN_DIR:$PATH

cd $PEGASUS_SUBMIT_DIR

# use a temp file for the message body
TMPFILE=`mktemp -t pegasus-notification.XXXXXXXXXX` || exit 1

cat >>$TMPFILE <<EOF
The following workflow is ending:

  $PEGASUS_SUBMIT_DIR

Below is output from pegasus-status.

EOF

pegasus-status -v >>$TMPFILE 2>&1
echo >>$TMPFILE

EXTRA_ARGS=""

if [ "X$NOTIFICATION_EMAIL" != "X" ]; then
    cat $TMPFILE | mailx -s "Workflow event: $PEGASUS_EVENT  $PEGASUS_SUBMIT_DIR" $EXTRA_ARGS $NOTIFICATION_EMAIL
fi

rm -f $TMPFILE


