#!/bin/bash

# This script is called when a workflow starts
# See https://pegasus.isi.edu/documentation/notifications.php

NOTIFICATION_EMAIL=$1

sleep 60s

export PATH=$PEGASUS_BIN_DIR:$PATH

cd $PEGASUS_SUBMIT_DIR

# use a temp file for the message body
TMPFILE=`mktemp -t pegasus-notification.XXXXXXXXXX` || exit 1

cat >>$TMPFILE <<EOF
The following workflow is starting up:

  $PEGASUS_SUBMIT_DIR

Below is output from pegasus-status.

EOF

pegasus-status -v >>$TMPFILE 2>&1
echo >>$TMPFILE

EXTRA_ARGS=""

# workflow images in the start message
DAG_FS=`du -s -b *.dag | awk '{print $1;}'`
if [ $DAG_FS -lt 1000000 ]; then
    if [ ! -e dax.png ]; then
        pegasus-graphviz -o dag.dot *.dag
        /usr/bin/dot -Tpng -odag.png dag.dot
        if [ -e dag.png ]; then
            EXTRA_ARGS="$EXTRA_ARGS -a dag.png"
        fi
    
        pegasus-graphviz -o dax.dot dax.xml
        /usr/bin/dot -Tpng -odax.png dax.dot
        if [ -e dax.png ]; then
            EXTRA_ARGS="$EXTRA_ARGS -a dax.png"
        fi
    fi
fi

if [ "X$NOTIFICATION_EMAIL" != "X" ]; then
    cat $TMPFILE | mailx -s "Workflow event: $PEGASUS_EVENT  $PEGASUS_SUBMIT_DIR" $EXTRA_ARGS $NOTIFICATION_EMAIL
fi

rm -f $TMPFILE

