#!/bin/bash

# This script is called when a workflow exits (successfully or after failure)
# See https://pegasus.isi.edu/documentation/notifications.php

echo "$PEGASUS_SUBMIT_DIR ended with $PEGASUS_STATUS" >>/tmp/mats-test

